/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { WhalePosition, WhaleState } from 'dsh-whale-companion/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$7768616c65436f6d70616e696f6e {
    export: () => Promise<RemoteResult<string>>
    get: () => Promise<RemoteResult<WhaleState>>
    import: (payload: string) => Promise<RemoteResult<WhaleState>>
    reset: () => Promise<RemoteResult<WhaleState>>
    setPosition: (position: WhalePosition) => Promise<RemoteResult<WhaleState>>
    setSkin: (skin: WhaleState['skin']) => Promise<RemoteResult<WhaleState>>
  }
  interface TypertRemoteMap {
    'whaleCompanion/export': () => Promise<RemoteResult<string>>
    'whaleCompanion/get': () => Promise<RemoteResult<WhaleState>>
    'whaleCompanion/import': (payload: string) => Promise<RemoteResult<WhaleState>>
    'whaleCompanion/reset': () => Promise<RemoteResult<WhaleState>>
    'whaleCompanion/setPosition': (position: WhalePosition) => Promise<RemoteResult<WhaleState>>
    'whaleCompanion/setSkin': (skin: WhaleState['skin']) => Promise<RemoteResult<WhaleState>>
  }
  interface TypertRemoteNamespaceMap {
    'whaleCompanion': TypertRemoteNamespace$7768616c65436f6d70616e696f6e
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
