/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_whale_companion_whaleCompanion_export_result$schema = z.string()
const dsh_whale_companion_whaleCompanion_get_result$schema = z.object({
  'version': z.literal(1),
  'xp': z.number(),
  'level': z.number(),
  'turns': z.number(),
  'sessions': z.number(),
  'tools': z.number(),
  'streak': z.number(),
  'longestStreak': z.number(),
  'checkpoints': z.array(z.string()),
  'achievements': z.array(z.union([z.literal("first-swim"), z.literal("ten-turns"), z.literal("century"), z.literal("week-current"), z.literal("month-tide"), z.literal("level-five"), z.literal("level-ten"), z.literal("tool-diver"), z.literal("early-bird"), z.literal("night-owl"), z.literal("steady-fin"), z.literal("collector")])),
  'skin': z.union([z.literal("ocean"), z.literal("coral"), z.literal("midnight"), z.literal("aurora"), z.literal("sunset"), z.literal("nebula")]),
  'position': z.object({
  'x': z.number(),
  'y': z.number(),
}),
  'updatedAt': z.number(),
  'lastActiveDay': z.union([z.undefined(), z.string()]).optional(),
})
const dsh_whale_companion_whaleCompanion_import_parameter_0$schema = z.string()
const dsh_whale_companion_whaleCompanion_import_result$schema = z.object({
  'version': z.literal(1),
  'xp': z.number(),
  'level': z.number(),
  'turns': z.number(),
  'sessions': z.number(),
  'tools': z.number(),
  'streak': z.number(),
  'longestStreak': z.number(),
  'checkpoints': z.array(z.string()),
  'achievements': z.array(z.union([z.literal("first-swim"), z.literal("ten-turns"), z.literal("century"), z.literal("week-current"), z.literal("month-tide"), z.literal("level-five"), z.literal("level-ten"), z.literal("tool-diver"), z.literal("early-bird"), z.literal("night-owl"), z.literal("steady-fin"), z.literal("collector")])),
  'skin': z.union([z.literal("ocean"), z.literal("coral"), z.literal("midnight"), z.literal("aurora"), z.literal("sunset"), z.literal("nebula")]),
  'position': z.object({
  'x': z.number(),
  'y': z.number(),
}),
  'updatedAt': z.number(),
  'lastActiveDay': z.union([z.undefined(), z.string()]).optional(),
})
const dsh_whale_companion_whaleCompanion_reset_result$schema = z.object({
  'version': z.literal(1),
  'xp': z.number(),
  'level': z.number(),
  'turns': z.number(),
  'sessions': z.number(),
  'tools': z.number(),
  'streak': z.number(),
  'longestStreak': z.number(),
  'checkpoints': z.array(z.string()),
  'achievements': z.array(z.union([z.literal("first-swim"), z.literal("ten-turns"), z.literal("century"), z.literal("week-current"), z.literal("month-tide"), z.literal("level-five"), z.literal("level-ten"), z.literal("tool-diver"), z.literal("early-bird"), z.literal("night-owl"), z.literal("steady-fin"), z.literal("collector")])),
  'skin': z.union([z.literal("ocean"), z.literal("coral"), z.literal("midnight"), z.literal("aurora"), z.literal("sunset"), z.literal("nebula")]),
  'position': z.object({
  'x': z.number(),
  'y': z.number(),
}),
  'updatedAt': z.number(),
  'lastActiveDay': z.union([z.undefined(), z.string()]).optional(),
})
const dsh_whale_companion_whaleCompanion_setPosition_parameter_0$schema = z.object({
  'x': z.number(),
  'y': z.number(),
})
const dsh_whale_companion_whaleCompanion_setPosition_result$schema = z.object({
  'version': z.literal(1),
  'xp': z.number(),
  'level': z.number(),
  'turns': z.number(),
  'sessions': z.number(),
  'tools': z.number(),
  'streak': z.number(),
  'longestStreak': z.number(),
  'checkpoints': z.array(z.string()),
  'achievements': z.array(z.union([z.literal("first-swim"), z.literal("ten-turns"), z.literal("century"), z.literal("week-current"), z.literal("month-tide"), z.literal("level-five"), z.literal("level-ten"), z.literal("tool-diver"), z.literal("early-bird"), z.literal("night-owl"), z.literal("steady-fin"), z.literal("collector")])),
  'skin': z.union([z.literal("ocean"), z.literal("coral"), z.literal("midnight"), z.literal("aurora"), z.literal("sunset"), z.literal("nebula")]),
  'position': z.object({
  'x': z.number(),
  'y': z.number(),
}),
  'updatedAt': z.number(),
  'lastActiveDay': z.union([z.undefined(), z.string()]).optional(),
})
const dsh_whale_companion_whaleCompanion_setSkin_parameter_0$schema = z.union([z.literal("ocean"), z.literal("coral"), z.literal("midnight"), z.literal("aurora"), z.literal("sunset"), z.literal("nebula")])
const dsh_whale_companion_whaleCompanion_setSkin_result$schema = z.object({
  'version': z.literal(1),
  'xp': z.number(),
  'level': z.number(),
  'turns': z.number(),
  'sessions': z.number(),
  'tools': z.number(),
  'streak': z.number(),
  'longestStreak': z.number(),
  'checkpoints': z.array(z.string()),
  'achievements': z.array(z.union([z.literal("first-swim"), z.literal("ten-turns"), z.literal("century"), z.literal("week-current"), z.literal("month-tide"), z.literal("level-five"), z.literal("level-ten"), z.literal("tool-diver"), z.literal("early-bird"), z.literal("night-owl"), z.literal("steady-fin"), z.literal("collector")])),
  'skin': z.union([z.literal("ocean"), z.literal("coral"), z.literal("midnight"), z.literal("aurora"), z.literal("sunset"), z.literal("nebula")]),
  'position': z.object({
  'x': z.number(),
  'y': z.number(),
}),
  'updatedAt': z.number(),
  'lastActiveDay': z.union([z.undefined(), z.string()]).optional(),
})

export const TYPERT = {
  package: 'dsh-whale-companion',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-whale-companion#whaleCompanion/export',
      service: 'whaleCompanion',
      namespace: 'whaleCompanion',
      method: 'export',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-whale-companion#whaleCompanion/export:result',
        schema: dsh_whale_companion_whaleCompanion_export_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-whale-companion/src/index.ts","line":75,"column":9},
    },
    {
      id: 'dsh-whale-companion#whaleCompanion/get',
      service: 'whaleCompanion',
      namespace: 'whaleCompanion',
      method: 'get',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-whale-companion/types#WhaleState',
        schema: dsh_whale_companion_whaleCompanion_get_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-whale-companion/src/index.ts","line":57,"column":9},
    },
    {
      id: 'dsh-whale-companion#whaleCompanion/import',
      service: 'whaleCompanion',
      namespace: 'whaleCompanion',
      method: 'import',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'payload',
          wire: 'payload',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-whale-companion#whaleCompanion/import:payload',
            schema: dsh_whale_companion_whaleCompanion_import_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-whale-companion/types#WhaleState',
        schema: dsh_whale_companion_whaleCompanion_import_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-whale-companion/src/index.ts","line":81,"column":9},
    },
    {
      id: 'dsh-whale-companion#whaleCompanion/reset',
      service: 'whaleCompanion',
      namespace: 'whaleCompanion',
      method: 'reset',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-whale-companion/types#WhaleState',
        schema: dsh_whale_companion_whaleCompanion_reset_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-whale-companion/src/index.ts","line":87,"column":9},
    },
    {
      id: 'dsh-whale-companion#whaleCompanion/setPosition',
      service: 'whaleCompanion',
      namespace: 'whaleCompanion',
      method: 'setPosition',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'position',
          wire: 'position',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-whale-companion/types#WhalePosition',
            schema: dsh_whale_companion_whaleCompanion_setPosition_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-whale-companion/types#WhaleState',
        schema: dsh_whale_companion_whaleCompanion_setPosition_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-whale-companion/src/index.ts","line":69,"column":9},
    },
    {
      id: 'dsh-whale-companion#whaleCompanion/setSkin',
      service: 'whaleCompanion',
      namespace: 'whaleCompanion',
      method: 'setSkin',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'skin',
          wire: 'skin',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-whale-companion#whaleCompanion/setSkin:skin',
            schema: dsh_whale_companion_whaleCompanion_setSkin_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-whale-companion/types#WhaleState',
        schema: dsh_whale_companion_whaleCompanion_setSkin_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-whale-companion/src/index.ts","line":63,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Local progress derived only from event type, sequence, timestamp, and Session id.",
        "summary": "Local progress derived only from event type, sequence, timestamp, and Session id.",
        "tags": [],
        "jsDoc": "/** Local progress derived only from event type, sequence, timestamp, and Session id. */",
        "key": "whaleCompanion",
        "exportName": "WhaleCompanionService",
        "members": [
          {
            "kind": "method",
            "name": "get",
            "signature": "@Remote('get') async get(): Promise<WhaleState>"
          },
          {
            "kind": "method",
            "name": "setSkin",
            "signature": "@Remote('setSkin') async setSkin(skin: WhaleState['skin']): Promise<WhaleState>"
          },
          {
            "kind": "method",
            "name": "setPosition",
            "signature": "@Remote('setPosition') async setPosition(position: WhalePosition): Promise<WhaleState>"
          },
          {
            "kind": "method",
            "name": "export",
            "signature": "@Remote('export') async export(): Promise<string>"
          },
          {
            "kind": "method",
            "name": "import",
            "signature": "@Remote('import') async import(payload: string): Promise<WhaleState>"
          },
          {
            "kind": "method",
            "name": "reset",
            "signature": "@Remote('reset') async reset(): Promise<WhaleState>"
          }
        ],
        "types": [
          {
            "name": "WhalePosition",
            "declaration": "export type WhalePosition = z.infer<typeof whalePositionSchema>;"
          },
          {
            "name": "WhaleState",
            "declaration": "export type WhaleState = z.infer<typeof whaleStateSchema>;"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
